name:                Haskall-RISCV
version:             0.1.0.0
github:              "C0L/Haskall-RISCV"
license:             BSD3
author:              "Colin Drewes"
maintainer:          "colindrewes@gmail.com"
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Haskall-RISCV#readme>

dependencies:
- base >= 4.7 && < 5
- array
- mtl

library:
  source-dirs: src

executables:
  Haskall-RISCV-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskall-RISCV

tests:
  Haskall-RISCV-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskall-RISCV
